spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     url:  jdbc:mysql://127.0.0.1:3306/studentsystem?serverTimezone=UTC
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.you.mybatisplus.mapper: debug
    com.you.mybatisplus.test: debug
    com.you.system.mapper: debug
    com.you.system.test: debug
server:
  port: 7071
mybatis-plus:
  configuration:
    cache-enabled: false
    use-deprecated-executor: false


#myQueueName: queue1

#mybatis-plus:
#  global-config:
#    db-config:
#      cl
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
